version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    groups:
      mantine:
        patterns:
          - "@mantine/*"
      vite:
        patterns:
          - "*vite*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      inertia:
        patterns:
          - "@inertiajs/*"
      tabler:
        patterns:
          - "@tabler/*"

  - package-ecosystem: composer
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: weekly
    groups:
      laravel:
        patterns:
          - "laravel/*"
      symfony:
        patterns:
          - "symfony/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
